#pragma once

#include <pch.h>
#include "../data_structures/Queue.h"

typedef GLFWwindow* screen;
typedef unsigned int uint;
typedef unsigned long ulong;
typedef unsigned char uchar;

namespace bndr {

	void ErrorCallback(int code, const char* message);
	BNDR_API void ClearGLErrors();
	BNDR_API void CheckGLError();
	// WARNING: this function can cause memory leaks! Make sure you use delete[] on the pointer to free the memory when you are done!
	std::pair<std::pair<uint, uint>, uchar*> LoadBitMap(const char* filePath);
	// WARNING: this function can cause memory leaks! Make sure you use delete[] on the pointer to free the memory when you are done!
	// image data must be of shape (255, 255, 3) or in other words an RGB image generated by LoadBitMap
	//uchar* ConvertRGBToRGBA(uchar* imageData, uint size);

	enum WindowStates {

		WINDOW_CLOSE = 0x01
	};

	class BNDR_API Window {
	
		screen window;
		// the aspect ratio
		float aspect;
		uint windowFlags = 0x0;

	public:

		Window(int x, int y, int width, int height, const char* title);
		// inline functions meant to abstract glfw functionality from the bndr namespace

		// state-checking methods

		// flush the display
		inline void Flush() { glfwSwapBuffers(window); }
		// check for events
		inline void PollEvents() { glfwPollEvents(); }
		// check if the window is currently open
		inline bool IsOpen() { return !glfwWindowShouldClose(window); }
		// set the close flag to true (useful for user-defined quit scenarios)
		inline void QuitWindow() { windowFlags = windowFlags | WINDOW_CLOSE; }
		// get the mouse cursor position
		std::pair<float, float> GetCursorPos();
		// updates flags regarding the window and whether or not the user has quit
		// returns true if the window is still open
		bool Update();

		// rendering methods

		// set the clear screen color
		inline void SetClearColor(float red, float green, float blue, float alpha) { glClearColor(red, green, blue, alpha); }
		// clear the screen
		inline void Clear() { glClear(GL_COLOR_BUFFER_BIT); }

		// customization

		// destroy GLFW window and terminate GLFW
		~Window();

	};
}

